<?php
/**
 * Copyright (C) 2021 Merchant's Edition GbR
 * Copyright (C) 2017-2018 thirty bees
 * Copyright (C) 2007-2016 PrestaShop SA
 *
 * NOTICE OF LICENSE
 *
 * This source file is subject to the Open Software License (OSL 3.0)
 * that is bundled with this package in the file LICENSE.md.
 * It is also available through the world-wide-web at this URL:
 * https://opensource.org/licenses/osl-3.0.php
 * If you did not receive a copy of the license and are unable to
 * obtain it through the world-wide-web, please send an email
 * to contact@merchantsedition.com so we can send you a copy immediately.
 *
 * @author    Merchant's Edition <contact@merchantsedition.com>
 * @author    thirty bees <contact@thirtybees.com>
 * @author    PrestaShop SA <contact@prestashop.com>
 * @copyright 2021 Merchant's Edition GbR
 * @copyright 2017-2018 thirty bees
 * @copyright 2007-2016 PrestaShop SA
 * @license   Open Software License (OSL 3.0)
 * PrestaShop is an internationally registered trademark of PrestaShop SA.
 * thirty bees is an extension to the PrestaShop software by PrestaShop SA.
 */

$this->displayTemplate('header')
?>

<!-- License agreement -->
<h2 id="licenses-agreement"><?php echo $this->l('License Agreements') ?></h2>
<p><strong><?php echo $this->l('To enjoy the many features that are offered for free by thirty bees, please read the license terms below. thirty bees core is licensed under OSL 3.0, while the modules and themes are licensed under AFL 3.0.') ?></strong></p>
<div style="height:200px; border:1px solid #ccc; margin-bottom:8px; padding:5px; background:#fff; overflow: auto; overflow-x:hidden; overflow-y:scroll;">
<?php $this->displayTemplate('license_content'); ?>
</div>

<div>
	<input type="checkbox" id="set_license" class="required" name="license_agreement" value="1" style="vertical-align: middle;float:left" <?php if ($this->session->licenseAgreement): ?>checked="checked"<?php endif; ?> />
	<div style="float:left;width:600px;margin-left:8px"><label for="set_license"><strong><?php echo $this->l('I agree to the above terms and conditions.') ?></strong></label></div>
</div>

<?php $this->displayTemplate('footer') ?>
