# <Module Name>

<short description>

## Description

<full description>

## License

This software is published under the [Academic Free License 3.0](https://opensource.org/licenses/afl-3.0.php)

## Contributing

Merchant's Edition modules are Open Source extensions to the Merchant's Edition e-commerce solution. Everyone is welcome and even encouraged to contribute with their own improvements.

For details, see [CONTRIBUTING.md](https://github.com/merchantsedition/merchantsedition/blob/1.9.1/CONTRIBUTING.md) in the core repository.

## Packaging

To build a package for the Merchant's Edition distribution machinery or suitable for importing it into a shop, run `tools/buildmodule.sh` of the Merchant's Edition core repository from inside the module root directory.

For module development, one clones this repository into `modules/` of the shop, alongside the other modules. It should work fine without packaging.

## Roadmap

#### Short Term

* None currently.

#### Long Term

* None currently.
